config/routes.rb
Rails.application.routes.draw do
  root 'notes#home'

  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :notes, except: [:show] do
    collection do
      post :confirm
    end
  end

  resources :feeds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/note.rb
class Note < ApplicationRecord
  validates :content, presence: true, length:{maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord
  before_validation {email.downcase!}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence: true, length:{maximum: 50}
  validates :email, presence: true, length:{maximum: 255}, format: {with: VALID_EMAIL_REGEX}
  validates :password_digest, presence: true, length:{minimum: 6}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def new
  	@feed = Feed.new
  end

  def create
  	@feed = Feed.new(feed_params)
  	if @feed.save
  		flash[:success] = '投稿しました'
  		redirect_to feed_path(@feed.id)
  	else
  		render :new
  	end
  end

  def show
  	@feed = Feed.find(params[:id])
  end

  def index
  	@feeds = Feed.all
  end

  def destroy
  	@feed = Feed.find(params[:id])
  	@feed.destroy
  	flash[:success] = '削除しました'
  	redirect_to feeds_path
  end

  private
  def feed_params
  	params.require(:feed).permit(:image, :image_cache)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:edit, :update, :destroy]

  def index
    @notes = Note.order('created_at DESC').paginate(page: params[:page], per_page: 15)
  end

  def new
    if params[:back]
      @note = Note.new(note_params)
    else
      @note = Note.new
    end
  end

  def confirm
    @note = Note.new(note_params)
    render :new if @note.invalid?
  end

  def create  
    @note = Note.new(note_params)
    if @note.save
      flash[:success] = '投稿しました！'
      redirect_to notes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      flash[:info] = '編集しました！'
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    flash[:info] = '削除しました！'
    redirect_to notes_path
  end

  private
  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = 'ログインしました'
      redirect_to user_path(user)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    log_out
    flash[:info] = 'ログアウトしました'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = '登録完了'
      redirect_to users_path
    else
      render :new
    end
  end

  def show
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 15)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = '編集しました！'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = '削除しました！'
    redirect_to users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_or_confirm
    if action_name == 'new' || action_name == 'confirm'
      confirm_notes_path
    elsif action_name == 'edit'
      note_path
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/edit.html.erb
<h1>Edit Image</h1>

app/views/feeds/index.html.erb
<h1>Index image</h1>
<% @feeds.each do |feed| %>
	<ul>
		<li><%= image_tag(feed.image.url) %>
		<li><%= link_to '編集', edit_feed_path(feed.id) %></li>
		<li><%= link_to '削除', feed_path(feed.id), method: :delete, data: {confirm: '本当に削除しますか？'} %></li>
	</ul>
<% end %>

app/views/feeds/new.html.erb
<%= form_with(model: @feed, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :image %>
  <%= image_tag(@feed.image.url) if @feed.image.url.present?  %>
  <%= f.file_field :image, id: :feed_image %>
  <%= f.hidden_field :image_cache %>
  <%= f.submit  %>
<% end %>

app/views/feeds/show.html.erb
<h1>Show image</h1>
<%= image_tag @feed.image.url %>
<%= link_to '編集', edit_feed_path(@feed.id) %>
<%= link_to '削除', feed_path(@feed.id), method: :delete, data: {confirm: '本当に削除しますか？'} %>

app/views/layouts/_footer.html.erb
<footer>
    <p><small>&copy; Awesome Note</small></p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar-default">
        <div class="container-fluid row">   
            <%= link_to 'Awesome Note', root_path, id: "logo" %>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                    <li><%= link_to 'プロフィール', '#' %></li>
                    <li><%= link_to 'ユーザーリスト', users_path %></li>
                    <li><%= link_to '新規投稿', new_note_path %></li>
                    <li><%= link_to '投稿一覧', notes_path %></li>
                    <li><%= link_to '画像投稿', new_feed_path %></li>
                    <li><%= link_to '画像一覧', feeds_path %></li>
                    <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                <% else %>
                	<li><%= link_to '新規登録', new_user_path %></li>
                    <li><%= link_to 'ログイン', login_path %></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Awesome Note</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
  
    <body>
        <%= render 'layouts/header' %>

        <div class="container">
            <% flash.each do |msg_type, msg| %>
                <div class="alert alert-<%= msg_type %>">
                    <%= msg %>
                </div>
            <% end %>
            <%= yield %>
        </div>
        
        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: @note, url: new_or_confirm, local: true) do |f| %>
    
    <%= render 'shared/error_messages', object: f.object %>
    
    <div id="note-content">
        <div class="form-group">
            <%= f.label :content %>
            <%= f.text_field :content, class: "form-control" %>
        </div>
        <div class="note-submit">
            <%= f.submit class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/notes/_note.html.erb
<li>
    <h4><%= note.content %></h4>
    <div class="buttons">
        <small>
            <%= link_to '編集', edit_note_path(note.id) %>
            <%= link_to '削除', note_path(note.id), method: :delete, data: {confirm: '本当に削除しますか？'} %>
        </small>
    </div>
</li>

app/views/notes/confirm.html.erb
<div class="form-container col-center">
    <div class="page-header">
        <h2>以下の内容で送信します</h2>
    </div>
    <%= form_with(model: @note, url: notes_path, local: true) do |f| %>
        <%= f.hidden_field :content %>
        <div id="content-wrapper">
            <%= @note.content %>
        </div>
        <div class="note-submit">
            <%= f.submit 'OK', class: "btn btn-primary" %>
        </div>
    <% end %>

    <%= form_with(model: @note, url: new_note_path, method: :get, local: true) do |f| %>
        <%= f.hidden_field :content %>
        <div class="note-submit">
            <%= f.submit '戻る', class: "btn btn-secondary", name: 'back' %>
        </div>
    <% end %>
</div>

app/views/notes/edit.html.erb
<div class="row">
    <div class="col-md-8 col-center">
        <div class="page-header">
            <h1>編集</h1>
        </div>
        <%= render 'form' %>
    </div>
</div>

app/views/notes/home.html.erb
<div class="jumbotron">
    <h1>Welcome to Awesome Note!</h1>
    <br>
    <br>
    <p>ツイッターのパクリです。</p>
</div>

app/views/notes/index.html.erb
<div class="notes-container row">
    <div class="page-header">
        <h1>投稿一覧</h1>
    </div>
    <div class="col-center">
        <ul class="notes">
            <%= render @notes %>
        </ul>
    </div>
</div>
<div id="pagination">
    <%= will_paginate %>
</div>

app/views/notes/new.html.erb
<div class="row">
    <div class="col-md-8 col-center">
        <div class="page-header">
            <h1>新規投稿</h1>
        </div>
        <%= render 'form' %>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        <h2><%= object.errors.count %>件のエラーがあります！</h2>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>   
        </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">  
        <%= f.label :name %>
        <%= f.text_field :name , class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="submit_button">
        <%= f.submit class: "btn btn-primary form-control" %>
    </div>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= user.name %>
    <%= user.email %>
    <%= link_to '編集', edit_user_path(user.id) %>
    <%= link_to '削除', user_path(user.id), method: :delete, data: {confirm: '本当に削除しますか？'} %>
</li>

app/views/users/edit.html.erb
<h1>Edit</h1>

app/views/users/index.html.erb
<h1>Index</h1>
<ul>
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>New</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Show</h1>
名前: <%= @user.name %>
email: <%= @user.email %>